### ISSUE TITLE
Getting error Plum (battleye: query timeout) after install this program

### ISSUE THREAD

**Issue by g3nsvrv** [lieuweberg/rich-destiny#6] opened 2021-10-17 12:07 UTC
Before of the Anticheat works great, but now soon as I installed this program, and after a 10 minutes of play, I got the Plum error.

After uninstall from the control panel, remove the binaries and restart the computer everything goes normal again, I can play without issues.

**Comment by lieuweberg** [comment] 2021-10-17 12:14
Unfortunately unless multiple people have this issue, this cannot be confirmed. I'd try installing it again in the default location in a few days and see if it then errors again.

**Comment by g3nsvrv** [comment] 2021-10-17 12:27
just to let you know, I installed rich-destiny on the default location (%userprofile%), with AV on (defender), using the default values.

**Comment by lieuweberg** [comment] 2021-12-11 12:20
Closing because there have been no reports of this from anyone else.

**Closed as completed by lieuweberg** 2021-12-11 12:20 UTC
